# fly.toml app configuration file generated for message-board-110768 on 2023-07-06T17:06:11-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "message-board-110768"
primary_region = "sea"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
